openapi: 3.0.0
info:
  title: プロジェクト管理API
  description: "このAPIは、プロジェクト作成、ユーザー招待、通知管理、コミット管理などの機能を提供します。"
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: ローカルサーバー

paths:
  /uploads/{filename}:
    get:
      summary: "アップロードしたファイルを取得"
      description: "指定されたファイル名のファイルを取得します。"
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "ファイルを取得しました。"
        404:
          description: "ファイルが見つかりません。"

  /:
    get:
      summary: ホーム画面データ取得
      description: 認証済みユーザーがアクセス可能なホーム画面データを取得します。公開されているプロジェクトとユーザーの通知情報を含みます。
      parameters:
        - name: search
          in: query
          required: false
          schema:
            type: string
          description: 検索クエリ。プロジェクト名または説明で部分一致する文字列を検索します。
      responses:
        "200":
          description: 成功時にプロジェクトリストと通知リストを返します
          content:
            application/json:
              schema:
                type: object
                properties:
                  projects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: プロジェクトのID
                        name:
                          type: string
                          description: プロジェクト名
                        description:
                          type: string
                          description: プロジェクトの説明
                  notifications:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: 通知のID
                        message:
                          type: string
                          description: 通知メッセージ
  
  /login:
    post:
      summary: "ログインしてトークンを取得"
      description: "ユーザー名とパスワードで認証し、認証が成功した場合はトークンとユーザーIDを返します。"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: "ログインするためのユーザー名"
                  example: "example_user"
                password:
                  type: string
                  description: "ログインするためのパスワード"
                  example: "password123"
      responses:
        '200':
          description: "認証成功。トークンとユーザーIDを返します。"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: "認証トークン。次回以降のリクエストに使用します。"
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  user_id:
                    type: integer
                    description: "認証に成功したユーザーのID。"
                    example: 1
        '401':
          description: "認証失敗。ユーザー名またはパスワードが正しくありません。"

  /logout:
    get:
      summary: "ログアウト"
      description: "ユーザーがログアウトします。"
      responses:
        200:
          description: "ログアウトしました。"

  /register:
    post:
      summary: 新規ユーザーの登録
      description: ユーザー名、パスワード、および確認用パスワードを受け取り、新しいユーザーを登録します。パスワードと確認用パスワードが一致しない場合や、既に使用されているユーザー名の場合にはエラーメッセージを返します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: ユーザー名（一意である必要があります）
                  example: user123
                password:
                  type: string
                  description: ログイン時に使用するパスワード
                  example: secretpassword
                password2:
                  type: string
                  description: 確認用パスワード（passwordと一致する必要があります）
                  example: secretpassword
              required:
                - username
                - password
                - password2
      responses:
        '201':
          description: ユーザーが正常に登録されました
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ユーザー登録が完了しました。"
        '400':
          description: パスワードと確認用パスワードが一致しません
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "パスワードと確認用パスワードが一致しません。"
        '409':
          description: このユーザー名は既に使用されています
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "このユーザー名は既に使用されています。"

  /profile/{user_id}:
    get:
      summary: "プロフィール情報を取得"
      description: "指定されたユーザーIDのプロフィール情報とプロジェクト情報を取得します。"
      parameters:
        - name: user_id
          in: path
          required: true
          description: "取得するユーザーのID"
          schema:
            type: integer
      responses:
        '200':
          description: "プロフィール情報の取得に成功しました。"
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    description: "ユーザー名"
                  projects:
                    type: array
                    description: "ユーザーのプロジェクト一覧"
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: "プロジェクトID"
                        name:
                          type: string
                          description: "プロジェクト名"
                        latest_commit_image:
                          type: string
                          description: "最新のコミット画像のファイルパス"
                  profile_image:
                    type: string
                    description: "プロフィール画像のファイルパス。設定がない場合、デフォルト画像が表示されます。"
                  user_id:
                    type: integer
                    description: "ユーザーID"
        '404':
          description: "指定されたユーザーが存在しないか、プロフィール情報が見つかりません。"

    post:
      summary: "プロフィール画像を更新"
      description: "指定されたユーザーのプロフィール画像を更新します。画像はフォームデータとして送信してください。"
      parameters:
        - name: user_id
          in: path
          required: true
          description: "更新するユーザーのID"
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                profile_image:
                  type: string
                  format: binary
                  description: "アップロードするプロフィール画像ファイル"
      responses:
        '200':
          description: "プロフィール画像の更新に成功しました。"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "更新成功メッセージ"
        '400':
          description: "プロフィール画像が見つかりません。"
        '401':
          description: "認証が必要です。"

  /makeproject:
    post:
      summary: 新規プロジェクトの作成
      description: ユーザーが新しいプロジェクトを作成し、最初のコミットを追加するエンドポイントです。プロジェクト名、説明、タグ、コミットメッセージ、およびコミット画像を提供します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                  description: プロジェクトの名前
                project_description:
                  type: string
                  description: プロジェクトの説明
                tags:
                  type: string
                  description: プロジェクトに関連するタグ（カンマ区切り）
                commit_message:
                  type: string
                  description: コミットメッセージ
                commit_image:
                  type: string
                  format: binary
                  description: 最初のコミットの画像ファイル
      responses:
        "201":
          description: 成功時に作成されたプロジェクトのIDを返します
          content:
            application/json:
              schema:
                type: object
                properties:
                  project_id:
                    type: integer
                    description: 作成されたプロジェクトのID
        "400":
          description: 画像がアップロードされていない場合のエラーメッセージ
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 画像ファイルがアップロードされていない場合のエラーメッセージ

  /project/{project_id}:
    get:
      summary: プロジェクトの詳細情報の取得
      description: 指定したプロジェクトの詳細情報（名前、説明、公開状態、最新のコミット画像）を取得するエンドポイントです。
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: integer
          description: プロジェクトのID
      responses:
        "200":
          description: プロジェクトの詳細情報が正常に返されます
          content:
            application/json:
              schema:
                type: object
                properties:
                  project_id:
                    type: integer
                    description: プロジェクトのID
                  name:
                    type: string
                    description: プロジェクトの名前
                  description:
                    type: string
                    description: プロジェクトの説明
                  is_public:
                    type: boolean
                    description: プロジェクトの公開状態
                  latest_commit_image:
                    type: string
                    description: 最新のコミットの画像
    patch:
      summary: プロジェクトの公開状態の変更
      description: 指定したプロジェクトの公開状態（公開/非公開）を変更するエンドポイントです。
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: integer
          description: プロジェクトのID
      responses:
        "200":
          description: 公開状態の変更が正常に反映されます
    delete:
      summary: プロジェクトの削除
      description: 指定したプロジェクトを削除するエンドポイントです。
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: integer
          description: プロジェクトのID
      responses:
        "200":
          description: プロジェクトが正常に削除されます

  /project/{project_id}/invite:
    get:
      summary: "ユーザー検索"
      description: "検索クエリに基づいてユーザーを検索し、プロジェクトへの招待候補を表示します。"
      parameters:
        - name: project_id
          in: path
          required: true
          description: "プロジェクトID"
          schema:
            type: integer
        - name: search
          in: query
          required: false
          description: "検索クエリ。ユーザー名に含まれる文字列を指定"
          schema:
            type: string
      responses:
        '200':
          description: "検索結果のユーザー一覧を返します。"
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    description: "招待候補となるユーザーのリスト"
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: "ユーザーID"
                        username:
                          type: string
                          description: "ユーザー名"
        '404':
          description: "プロジェクトが見つかりません。"
    post:
      summary: "ユーザー招待"
      description: "指定されたユーザーをプロジェクトに招待し、通知を作成します。"
      parameters:
        - name: project_id
          in: path
          required: true
          description: "プロジェクトID"
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "招待するユーザーのID"
      responses:
        '200':
          description: "ユーザーがプロジェクトに招待され、通知が送信されました。"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "招待成功メッセージ"
        '404':
          description: "招待するユーザーが見つかりません。"

  /project/{project_id}/commit:
    post:
      summary: "プロジェクトへのコミットを追加"
      description: "指定されたプロジェクトに対してコミットを追加します。コミットメッセージと、オプションでコミット画像をアップロードできます。新しいコミットが追加されると、プロジェクトのメンバーに通知が送信されます。"
      parameters:
        - name: project_id
          in: path
          required: true
          description: "コミットを追加するプロジェクトのID"
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commit_message:
                  type: string
                  description: "コミットメッセージ"
                commit_image:
                  type: string
                  format: binary
                  description: "コミット画像（任意）"
      responses:
        '201':
          description: "コミットが正常に追加され、通知が送信されました。"
        '400':
          description: "コミット画像が指定されたが、アップロードに失敗しました。"
        '404':
          description: "指定されたプロジェクトが存在しません。"
        '401':
          description: "認証が必要です。"
        '500':
          description: "サーバーエラー"

  /project/{project_id}/commits:
    get:
      summary: プロジェクトのコミット履歴を取得
      description: 指定したプロジェクトのコミット履歴を取得するエンドポイントです。コミットメッセージ、コミット画像、投稿日時などが返されます。
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: integer
          description: プロジェクトのID
      responses:
        "200":
          description: プロジェクトのコミット履歴が返されます
          content:
            application/json:
              schema:
                type: object
                properties:
                  commits:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: コミットのID
                        commit_message:
                          type: string
                          description: コミットメッセージ
                        commit_image:
                          type: string
                          description: コミット画像のパス
                        date_posted:
                          type: string
                          format: date-time
                          description: コミットが投稿された日時

  /project/{project_id}/commit/{commit_id}:
    get:
      summary: コミット詳細情報の取得
      description: |
        指定したプロジェクトとコミットIDに関連するコミットの詳細情報を取得します。
        返される情報にはコミットメッセージ、関連するコメント、プロジェクト名、コミット画像、コミット日時などが含まれます。
      parameters:
        - name: project_id
          in: path
          description: プロジェクトのID
          required: true
          schema:
            type: integer
        - name: commit_id
          in: path
          description: コミットのID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: コミットの詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  project_id:
                    type: integer
                    description: プロジェクトID
                  project_name:
                    type: string
                    description: プロジェクト名
                  commit_id:
                    type: integer
                    description: コミットID
                  commit_message:
                    type: string
                    description: コミットメッセージ
                  commit_image:
                    type: string
                    description: コミット画像のパス（もしあれば）
                  date_posted:
                    type: string
                    format: date-time
                    description: コミットの投稿日時
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: コメントのID
                        content:
                          type: string
                          description: コメントの内容
                        created_at:
                          type: string
                          format: date-time
                          description: コメントが作成された日時
                        user:
                          type: object
                          properties:
                            id:
                              type: integer
                              description: コメントを投稿したユーザーのID
                            username:
                              type: string
                              description: コメントを投稿したユーザーの名前
        400:
          description: 不正なリクエスト（コメントの内容が空の場合など）
        404:
          description: プロジェクトまたはコミットが見つからない場合
    post:
      summary: コミットにコメントを追加
      description: |
        指定したコミットに新しいコメントを追加します。
        コメントはコミットIDに関連付けられ、プロジェクトのメンバーに通知されます。
      parameters:
        - name: project_id
          in: path
          description: プロジェクトのID
          required: true
          schema:
            type: integer
        - name: commit_id
          in: path
          description: コミットのID
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: コメントの内容
                  example: "This is a comment"
      responses:
        200:
          description: コメントが正常に追加され、通知が送信された
        400:
          description: コメント内容が空の場合
          
  /notification/{notification_id}/respond/{response}:
    patch:
      summary: "招待に対する応答"
      description: "ユーザーが通知を受け取り、その通知に対して招待を承諾または拒否するエンドポイントです。"
      parameters:
        - name: notification_id
          in: path
          required: true
          description: "通知のID"
          schema:
            type: integer
        - name: response
          in: path
          required: true
          description: "招待に対する応答（'accept' または 'decline'）"
          schema:
            type: string
      responses:
        '200':
          description: "招待の応答が成功しました"
        '404':
          description: "通知が見つかりませんでした"
